### PR TITLE
fix: resolving `.mjs` file extension

### LINKED ISSUE #100: Add support for import `.mjs` file
As the name suggested. I and other need this to work with Gleam gen code. Thanks

### PR DESCRIPTION
**Pull request by nmerget**
closes #100

### CODE REVIEW

File: bridge/jsb_module_resolver.cpp [hunk 1]
```diff
@@ -372,11 +380,11 @@ namespace jsb
                     {
                         const String dot = ".";
                         const String dot_slash = "./";
-                        const String& main = package_exports[key_main];
+                        const String& main = package_json[key_main];
```
Comment (Benjamin-Dobell) [inline bridge/jsb_module_resolver.cpp]: Looks like this snuck in from the other PR.

Comment (nmerget) [reply bridge/jsb_module_resolver.cpp]: good catch removed it

**Review by Benjamin-Dobell — APPROVED** [review]

**Comment by Benjamin-Dobell** [comment]
Sorry, auto-merge seems to have failed due to me merging your other PR that touches the same file.
